### ISSUE TITLE
Translated labels cannot be marked html_safe

### ISSUE THREAD

**Issue by mobilutz** [heartcombo/simple_form#1070]
I just upgraded from 3.0.0 to 3.0.2 and now I have a problem with html in my labels.

I define the html inside my I18n Yaml File like this:

```
simple_form:
  labels:
    defaults:
      test_label: '<span class="class">My Label</span>'
```

Now the new `html_safe` call to the labels breaks my views and I cannot fix it unless I move all my html labels to a helper or somewhere else.
But I don't think that that is practical.

Maybe there is a way to mark Yaml loaded translations without user inputs as html_safe?

Thanks in advance!
