### ISSUE TITLE
Custom default error message with simple_form is not loaded

### ISSUE THREAD

**Issue by Narf-stack** [heartcombo/simple_form#1718]
Hi,
I can't manage to change the default error message from simple form, i tried to edit the `simple_form.en.yml ` file. I used differents approachs but the outcome was still the same, my update was ignored. 
First, I simply tried to update the default_message variable, then I specified a default message according to the name of my models. I also tried to update the gem version from 4.1.0 to 5.0.3, but that was not enough.

Here is my current file :

en:
  simple_form:
    error_notification:
      default_message: "Original default message:"
      model_name: "A custom message:"

## Environment

- ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
-  Rails 5.2.3
- simple_form 4.1.0

## Current behavior
My custom error_notification message is ignored. I can only see the " Please review the problems below:" message

## Expected behavior
Using my custom message for error notifications.

**Comment by marcelolx** [comment]
@Narf-stack Could you provide a sample app reproducing the problem you are facing? I've tested this functionality here and it works as expected 🤔 

```yml
en:
  simple_form:
    error_notification:
      default_message: "Default generic error message"
```

![image](https://user-images.githubusercontent.com/20196775/100343784-97ae3400-2fbe-11eb-94ce-a0dee7779d58.png)

```yml
en:
  simple_form:
    error_notification:
      default_message: "Default generic error message"
      user: "Specific user error notification"
```

![image](https://user-images.githubusercontent.com/20196775/100343758-8ebd6280-2fbe-11eb-9554-13ae7791210e.png)
