### ISSUE TITLE
Hints don't work on the namespaced model

### ISSUE THREAD

**Issue by jonas-jasas** [heartcombo/simple_form#1828]
## Environment

- Ruby **3.2.1**
- Rails **7.0.8**
- Simple Form **5.3.0**

## Current behavior

Hints don't work for the namespaced models.

```yaml
en:
  simple_form:
    hints:
      myns/mymodel:
        email: Some text
```
