### ISSUE TITLE
SimpleForm hint: using key in the locale as attribute when in fact is a model

### ISSUE THREAD

**Issue by MarceloCajueiro** [heartcombo/simple_form#364]
Hey!

When I add a hint to an attribute of a particular model and I use an association input for this model the i18n is mistakenly displayed;

Very confusing explanation.

Let's see a real example:

``` yaml
  simple_form:
    hints:
      splitting:
        interval: "em dias"
```

``` erb
  <%= f.input :splitting %>
```

The hint is returned as `interval: em dias`

I created a test case for this: f3eabaf06e8dcd96f3ef26b409efc3832c193af0
