### ISSUE TITLE
ambiguity in locales for labels, units, etc.

### ISSUE THREAD

**Issue by fringd** [heartcombo/simple_form#384]
as things stand, there are some bugs and ambiguity in the locals for simpleform. the class names are clashing with default attribute labels.

imagine a property management app that manages deeds, titles, and documents. Now we might want to specify labels for the attributes of a "title" object:

```
en:
  simpleform:
    labels:
      title:
       property_name: ...
       execution_status: ...
```

but now my form for documents (which have a title attribute) looks like

```
document size: ______________
<#Hash 2l3kj2lk4jl24kj2l3kj...> : _______________
```

instead of 

```
document size: ________________
title: ________________
```

as a workaround you can define 'simpleform.labels.document.title' to be 'title', but this shouldn't be needed.

is it possible to detect that you've recieved a hash instead of a string and ignore the value? this would at least fix the bug.

even better, it would be awesome to have the default attributes moved out of the top level (documents:, properties:, etc) and into a "default" subsection

i.e. 

```
en:
  simple_form:
    labels:
      defaults:
        title: Please enter the Title
      document:
        title: Please enter the Document Title
      title:
        owner: ...
        property_address: ...
```

this would remove any ambiguity...
