### ISSUE TITLE
input_field does not add placeholders from the locales yaml file

### ISSUE THREAD

**Issue by 23inhouse** [heartcombo/simple_form#468]
Should the `input_field` helper method use the placeholders from the locales yaml file?

In the below example you can see the there is no placeholder for the input.

``` yml
en:
  simple_form:
    hints:
      blog:
        name: 'My hint in english'
    labels:
      blog:
        name: 'My english label'
    placeholders:
      blog:
        name: 'type your name here (in english)'
```

``` erb
<%= form.label attribute_name %>
<%= form.input_field attribute_name %>
<%= form.hint attribute_name %>
```

``` html
<label class="string required" for="blog_name"><abbr title="required">*</abbr> My english label</label>
<input class="string required" id="blog_name" name="blog[name]" size="50" type="text" value="My name" />
My hint in english
```
