### ISSUE TITLE
I18n lookups for namespaced models

### ISSUE THREAD

**Issue by carolfs** [heartcombo/simple_form#555]
In Rails, a namespaced model Module::Model becomes module/model in i18n lookups, but in simple_form only module_model works. For instance:

```
en:
  activerecord:
    attributes:
      module/model:
        attribute: attribute_translation
  simple_form:
    hints:
      module_model:
        attribute: attribute_hint
```

I believe translations in simple_form would be more consistent with Rails and easier to use if it also used module/model in i18n lookups.
