### ISSUE TITLE
i18n keyname for f.association 

### ISSUE THREAD

**Issue by chrissearle** [heartcombo/simple_form#679]
Suspect I'm missing something obvious here.

In the model:

``` ruby
  belongs_to :composer
```

On the view (haml):

``` ruby
    = f.input :title
    = f.input :soloists
    = f.association :composer
```

In the translation file:

``` yaml
    labels:
      defaults:
        title: 'Song Title'
        soloists: 'Soloist(s)'
        composer: 'Composer Name'
```

For the two text fields I get the correct i18n name
For the composer field - I get a real nice dropdown - but the label "Composer" - looks like it's the auto-generated name for fields without an i18n key.

Am not seeing what key needs to be given to match for form fields made with f.association - would love someone to point me in the right direction :)

Versions - rails 3.2.8, simple_form 2.0.4
