### ISSUE TITLE
Change the default error message with simple_form

### ISSUE THREAD

**Issue by vdaubry** [heartcombo/simple_form#768]
I don't manage to change the default error message from simple form, i tried to edit the simple form locale file but it seems to be ignored

Here is my locale file:

``` yaml
#config/locales/simple_form.en.yml
en:
  simple_form:
    error_notification:
      default_message: "A custom message:"
```

But i still get "Please review the problems below:"

Do you have any idea what i could be doing wrong ?

P.S: Using simple_form 2.0.4

Thanks for your help, Vincent.
